// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdezwftreygyoafirizz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZXp3ZnRyZXlneW9hZmlyaXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODY2OTksImV4cCI6MjA2MDM2MjY5OX0.SRSPgkWPfagvv_iYpt0a8Bd-8PfsAxdPU1N38rfAufM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);